// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV_E_EVxoEOU5KpMDi27QbHyscEZy8CRE',
    appId: '1:491044990888:web:039dde21981c937908379d',
    messagingSenderId: '491044990888',
    projectId: 'fir-d5aad',
    authDomain: 'fir-d5aad.firebaseapp.com',
    storageBucket: 'fir-d5aad.appspot.com',
    measurementId: 'G-PPCYKYB6HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqQbGXv9iaeyvgFn2qngv17isEBYsBcUM',
    appId: '1:491044990888:android:97dcfe77b367c85608379d',
    messagingSenderId: '491044990888',
    projectId: 'fir-d5aad',
    storageBucket: 'fir-d5aad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDIEjc3mrK5zG_av6zsog8lnRtnfEVLbA',
    appId: '1:491044990888:ios:e736467a07b4f7ca08379d',
    messagingSenderId: '491044990888',
    projectId: 'fir-d5aad',
    storageBucket: 'fir-d5aad.appspot.com',
    iosBundleId: 'com.example.applicationUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDIEjc3mrK5zG_av6zsog8lnRtnfEVLbA',
    appId: '1:491044990888:ios:2af7a25568f504f908379d',
    messagingSenderId: '491044990888',
    projectId: 'fir-d5aad',
    storageBucket: 'fir-d5aad.appspot.com',
    iosBundleId: 'com.example.applicationUts.RunnerTests',
  );
}
